version: '3'
services:
  identidock:
    image: daredevil192/identidock:latest
      ports:
        - "5000:5000"
    deploy:
      replicas: 1
    environment:
      ENV: DEV 
    links:
      - dnmonster
      - redis

  dnmonster:
    image: amouat/dnmonster:1.0
    deploy:
      replicas: 1

  redis:
    image: redis:3.0
    deploy:
      replicas: 1