version: '3'
services:
  identidock.api:
    image: daredevil192/identidock:latest
      ports:
      - "5000:5000"
    environment:
      ENV: DEV 
    volumes:
    - ./app:/app
    links:
    - dnmonster
    - redis

  dnmonster.api:
    image: amouat/dnmonster:1.0

  redis.api:
    image: redis:3.0